name: I added an engine detection
labels: ["Type: Engine"]
body:
- type: textarea
  attributes:
    label: SteamDB links
    description: Link a few app pages that use this engine.
  validations:
    required: true

- type: textarea
  attributes:
    label: Some reference to the engine, such as the developer site or a wikipedia article.
  validations:
    required: true
