name: Test rules

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: php8.0 tests/Test.php
    - name: Test (two pass)
      run: php8.0 tests/Test2Pass.php
